services:
  accounts:
    image: "onrcanogul/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mynetwork
  loans:
    image: "onrcanogul/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mynetwork
  cards:
    image: "onrcanogul/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: "bridge"